version: "3"

services: 
  frontend:
    image: frontend
    restart: always
    stdin_open: true
    ports:
      - "3000:3000"
    
    working_dir: /frontend/src/app

    volumes: 
      - ./frontend:/frontend/src/app

    entrypoint: ["npm","start"]
    links: 
      - backend
    networks: 
      - webappnetwork

  backend:
    image: backend
    restart: always
    ports: 
      - "5000:5000"
      
    volumes:
      - ./backend:/backend

    depends_on:
      - mongo
    networks: 
      - webappnetwork

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    volumes:
      - mongo-data:/data/db

    ports:
      - "27017:27017"
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge

volumes: 
  mongo-data:
    driver: local

